### ISSUE TITLE
Code execution

### ISSUE THREAD

**Issue by pokaxpoka** [deepmind/ai-safety-gridworlds#3]
When I try to run the code, e.g., PYTHONPATH=. python -B ai_safety_gridworlds/environments/safe_interruptibility.py, the following error occurs even though I follow the same setting in README, i.e., python=2.7.13 with enum34 and numpy=1.13.3. Can I get a solution for this error?

Thanks in advance

**Comment by miljanm** [comment]
Hi, could you please attach the error stack trace?

**Comment by pokaxpoka** [comment]
Here is my error message:
====
Traceback (most recent call last):
  File "ai_safety_gridworlds/environments/safe_interruptibility.py", line 287, in <module>
    app.run(main)
  File "/home/km/anaconda3/envs/saferl/lib/python2.7/site-packages/absl/app.py", line 274, in run
    _run_main(main, argv)
  File "/home/km/anaconda3/envs/saferl/lib/python2.7/site-packages/absl/app.py", line 238, in _run_main
    sys.exit(main(argv))
  File "ai_safety_gridworlds/environments/safe_interruptibility.py", line 284, in main
    ui.play(env)
  File "/home/km/sample_codes/ai-safety-gridworlds/ai_safety_gridworlds/environments/shared/safety_ui.py", line 86, in play
    curses.wrapper(self._init_curses_and_play)
  File "/home/km/anaconda3/envs/saferl/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/km/sample_codes/ai-safety-gridworlds/ai_safety_gridworlds/environments/shared/safety_ui.py", line 173, in _init_curses_and_play
    elapsed=datetime.timedelta())
  File "/home/km/sample_codes/ai-safety-gridworlds/pycolab/human_ui.py", line 333, in _display
    for row, board_line in enumerate(observation.board, start=1):
AttributeError: 'numpy.ndarray' object has no attribute 'board'
====
Thanks!

**Comment by pokaxpoka** [comment]
I think that the codes in my pycolab directory are different from codes on your repository. How can I get the synchronized codes? (Because pycolab directory is empty when I clone the repository, I copy the codes in https://github.com/deepmind/pycolab.git)

Thanks!

**Comment by miljanm** [comment]
The error you have is because you're using a version of pycolab that is commited at master, which is different from the one we use.

When cloning ai-safety-gridworlds, have you made sure to include `--recursive` flag? As in `git clone --recursive https://github.com/deepmind/ai-safety-gridworlds.git`. This will make sure you get a correct version of pycolab as a submodule.

If that for some reason doesn't work, then once you clone ai-safety-gridworlds, do
```
cd ai-safety-gridworlds/
rm pycolab  # In case the folder exists already.
git clone https://github.com/deepmind/pycolab.git
cd pycolab/
git checkout b389d1e7ef949863561047d358a1661c298d382f
git reset --hard
```

This will give you the correct pycolab version.

**Comment by pokaxpoka** [comment]
Thanks for the clarification! It's working now.
